apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl31
  labels:
    pod: depl31
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task03
  template:
    metadata:
      labels:
        app: task03
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
#        ports:
#        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 80
        env:
          - name: HTTP_PORT
            value: "81"
