apiVersion: v1
kind: Service
metadata:
  name: svc3
spec:
  selector:
    app: task03
  ports:
  - name: http
    protocol: TCP
    port: 81
    targetPort: 80
  - name: http2
    protocol: TCP
    port: 1180
    targetPort: 80
  - name: https
    protocol: TCP
    port: 11443
    targetPort: 443
  externalIPs:
    - 192.168.1.11
