apiVersion: v1
kind: Service
metadata:
  name: svc04-nodeport
spec:
  type: NodePort
  selector:
    app: task04
  ports:
  - name: http1
    protocol: TCP
    port: 80
    nodePort: 30001
  - name: http2
    protocol: TCP
    port: 8080
    nodePort: 30081
  externalIPs:
    - 192.168.120.100
